// Package id provides thread-safe ULID generation for all Flicko entities.
//
// Why ULID over UUID v4:
//   - Lexicographically sortable (encodes timestamp)
//   - 48-bit ms timestamp + 80-bit randomness
//   - Compatible with PostgreSQL TEXT columns and INDEX ordering
//   - Cursor pagination works: WHERE id < $cursor ORDER BY id DESC
//   - No coordination needed (unlike Snowflake IDs)
//
// Why not UUID v7 (also time-sortable):
//   - ULID is 26 chars (Crockford Base32) vs 36 chars (UUID hex+hyphens)
//   - Smaller index footprint in Postgres
//   - Better human readability
package id

import (
	"crypto/rand"
	"io"
	"sync"
	"time"

	"github.com/oklog/ulid/v2"
)

// generator is a package-level, thread-safe ULID generator.
// Uses a pooled entropy source to avoid lock contention.
//
// Under load (300 msg/sec), rand.Reader with a mutex would become
// a bottleneck. The pool gives each goroutine its own entropy reader.
var generator = &ulidGenerator{
	entropyPool: sync.Pool{
		New: func() interface{} {
			return &lockedReader{reader: rand.Reader}
		},
	},
}

type ulidGenerator struct {
	entropyPool sync.Pool
}

type lockedReader struct {
	mu     sync.Mutex
	reader io.Reader
}

func (r *lockedReader) Read(p []byte) (n int, err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.reader.Read(p)
}

// New generates a new ULID string.
// Thread-safe, suitable for concurrent use from any goroutine.
// Panics are theoretically impossible (crypto/rand on Linux uses
// getrandom(2)), but we handle them defensively.
func New() string {
	entropy := generator.entropyPool.Get().(*lockedReader)
	defer generator.entropyPool.Put(entropy)

	id, err := ulid.New(ulid.Timestamp(time.Now()), entropy)
	if err != nil {
		// This should never happen with crypto/rand, but if it does,
		// fall back to a timestamp-only ULID (unique to the ms).
		// Collision risk: only if two calls in same ms both fail,
		// which implies crypto/rand is broken (bigger problems).
		id = ulid.MustNew(ulid.Timestamp(time.Now()), nil)
	}

	return id.String()
}

// MustParse parses a ULID string. Panics on invalid input.
// Use only when the ULID was previously generated by us (trusted source).
func MustParse(s string) ulid.ULID {
	return ulid.MustParse(s)
}

// Parse parses a ULID string, returning an error if invalid.
// Use for validating user-supplied ULIDs (untrusted input).
func Parse(s string) (ulid.ULID, error) {
	return ulid.Parse(s)
}

// IsValid checks if a string is a valid ULID.
// Useful in request validation before hitting the database.
func IsValid(s string) bool {
	if len(s) != 26 {
		return false
	}
	_, err := ulid.Parse(s)
	return err == nil
}

// Timestamp extracts the Unix millisecond timestamp from a ULID string.
// Returns 0 if the ULID is invalid.
func Timestamp(s string) time.Time {
	parsed, err := ulid.Parse(s)
	if err != nil {
		return time.Time{}
	}
	return ulid.Time(parsed.Time())
}
