include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/features/sonic_music/localization/app_localizations_*.dart"
    - "packages/**"
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    text_direction_code_point_in_literal: ignore
    experimental_member_use: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
    invalid_annotation_target: ignore
    todo: ignore

linter:
  rules:
    avoid_print: false
