package lock

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
)

type LockService interface {
	AcquireLock(ctx context.Context, key, token string, ttl time.Duration) (bool, error)
	ReleaseLock(ctx context.Context, key, token string) error
}

type lockService struct {
	redisClient *redis.Client
	logger      *zap.Logger
}

func NewLockService(rc *redis.Client, logger *zap.Logger) LockService {
	return &lockService{
		redisClient: rc,
		logger:      logger,
	}
}

// Lua script to safely release a lock only if the token matches (prevents releasing someone else's lock)
const releaseLockLua = `
if redis.call("get", KEYS[1]) == ARGV[1] then
    return redis.call("del", KEYS[1])
else
    return 0
end
`

// AcquireLock attempts to acquire a distributed lock using Redis SET NX.
// The token should be a unique UUID generated by the caller.
func (s *lockService) AcquireLock(ctx context.Context, key, token string, ttl time.Duration) (bool, error) {
	_, err := s.redisClient.SetArgs(ctx, key, token, redis.SetArgs{
		Mode: "NX",
		TTL:  ttl,
	}).Result()

	if err != nil {
		if err == redis.Nil {
			return false, nil
		}
		s.logger.Error("failed to execute lock acquire", zap.Error(err), zap.String("key", key))
		return false, err
	}
	return true, nil
}

// ReleaseLock executes a Lua script to atomically read and delete the lock ONLY if the token matches.
func (s *lockService) ReleaseLock(ctx context.Context, key, token string) error {
	_, err := s.redisClient.Eval(ctx, releaseLockLua, []string{key}, token).Result()
	if err != nil && err != redis.Nil {
		s.logger.Error("failed to execute lock release", zap.Error(err), zap.String("key", key))
		return err
	}
	return nil
}
