name: Dart & Flutter CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mobile/**'

permissions:
  contents: read

jobs:
  build:
    name: Dart & Flutter Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
          cache: true

      - name: Setup environment
        run: touch .env

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run unit tests
        run: flutter test
