name: Greetings

on: [pull_request_target, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: First Interaction Greeting
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Welcome First Contributor
        uses: actions/first-interaction@0223df1f044d033fa2d75a6c117bfa4911d9dbe3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome to Flicko! Thanks for opening an issue."
          pr-message: "Welcome to Flicko! Thanks for contributing your first pull request."
