name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '36 13 * * 5'

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Run Semgrep Standalone Scan
        run: semgrep scan --config auto --sarif --output semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28
        with:
          sarif_file: semgrep.sarif
        if: always()
